### ISSUE TITLE
AGM adds medical stuff twice

### ISSUE THREAD

**Issue by captainblaffer** [cptnnick/F3_PA#5]
add to AGM_clientInit.sqf line 15

player removeItems "AGM_Bandage";
player removeItems "AGM_Morphine";
player removeItems "AGM_Epipen";
player removeItems "AGM_Bloodbag";

**Comment by cptnnick** [comment]
https://github.com/ferstaberinde/F3/pull/537

You're making a ticket at the wrong repo : )
